//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnimeActivityMetrics) DeepCopyInto(out *AnimeActivityMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnimeActivityMetrics.
func (in *AnimeActivityMetrics) DeepCopy() *AnimeActivityMetrics {
	if in == nil {
		return nil
	}
	out := new(AnimeActivityMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnimeMonitor) DeepCopyInto(out *AnimeMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnimeMonitor.
func (in *AnimeMonitor) DeepCopy() *AnimeMonitor {
	if in == nil {
		return nil
	}
	out := new(AnimeMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnimeMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnimeMonitorList) DeepCopyInto(out *AnimeMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnimeMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnimeMonitorList.
func (in *AnimeMonitorList) DeepCopy() *AnimeMonitorList {
	if in == nil {
		return nil
	}
	out := new(AnimeMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnimeMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnimeMonitorSpec) DeepCopyInto(out *AnimeMonitorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnimeMonitorSpec.
func (in *AnimeMonitorSpec) DeepCopy() *AnimeMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(AnimeMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnimeMonitorStatus) DeepCopyInto(out *AnimeMonitorStatus) {
	*out = *in
	in.Metrics.DeepCopyInto(&out.Metrics)
	if in.TrendingAnime != nil {
		in, out := &in.TrendingAnime, &out.TrendingAnime
		*out = make([]TrendingAnime, len(*in))
		copy(*out, *in)
	}
	in.LastChecked.DeepCopyInto(&out.LastChecked)
	in.LastActivityChange.DeepCopyInto(&out.LastActivityChange)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnimeMonitorStatus.
func (in *AnimeMonitorStatus) DeepCopy() *AnimeMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(AnimeMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrendingAnime) DeepCopyInto(out *TrendingAnime) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrendingAnime.
func (in *TrendingAnime) DeepCopy() *TrendingAnime {
	if in == nil {
		return nil
	}
	out := new(TrendingAnime)
	in.DeepCopyInto(out)
	return out
}

